### PR TITLE
 Fix memory leak with regression test

### PR DESCRIPTION
**Pull request by Superoryco**
Fix memory leak with regression test
#20

### CODE REVIEW

**Comment by ljharb** [comment]
In the future, please do not open up duplicate PRs - post a link to your commit and I can add it to the original PR.

**Comment by Superoryco** [comment]
> In the future, please do not open up duplicate PRs - post a link to your commit and I can add it to the original PR.

Sorry about that...

It looks like jsdom has some environment conflicts with this repository, and I think it is necessary to be included during the test. How can I make it pass? @ljharb 

https://github.com/Superoryco/react-outside-click-handler/commit/b68c5512ee366277a700e5ccbd26fb929dcab5e6

**Comment by ljharb** [comment]
I'm not clear on why it's needed.

**Comment by Superoryco** [comment]
> I'm not clear on why it's needed.

In 1.2.3

If we mousedown on outside area without mouseup serval times, multiple zombie mouseup eventListener will be added to document. In next click cycle(mousedown then mouseup), these zombies will trigger props.onOutsideClick at the same time which should be an unexpected behavior.

#20 fixed the problem. To make a  regression test case, we need to trigger mouseup eventListener in document instead of call instance.onMouseUp(event);(This will call props.onOutsideClick only once but still leaves zombies unexposed).

      it('calls onOutsideClick only once', () => {
        const spy = sinon.spy();
        const wrapper = mount(<OutsideClickHandler onOutsideClick={spy} />);
        const instance = wrapper.instance();

        instance.childNode = {};
        expect(contains(instance.childNode, target)).to.equal(false);

        instance.onMouseDown(event);
        instance.onMouseDown(event);
        instance.onMouseDown(event);
        
        const mouseUpEvent = new Event('mouseup');
        document.dispatchEvent(mouseUpEvent);

        expect(spy).to.have.property('callCount', 1);
      });


document.dispatchEvent(mouseUpEvent) requires jsdom and so does onMouseDown function.
That's why I think jsdom is needed...

Any suggestions...?

**Comment by ljharb** [comment]
Instead of adding jsdom, can we mock `document.dispatchEvent`, or, just manually invoke prop functions to simulate what that does?

**Comment by Superoryco** [comment]
@ljharb Great...
But I have no idea how to make a fake `document.dispatchEvent` which may trigger event listeners.
How about this: 
Lets focus on the number of event listeners...
I made a document object with addEventListener & removeEventListener spy functions to check the count, is it a good approach?

**Comment by Superoryco** [comment]
By the way, why skip lifecycle methods? `  describe.skip('lifecycle methods', () => {`

**Pull request merged**
